# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vkHw4a5pawE_w8feMyOnUnCUekMUbdmv
"""

!pip install pyupbit
!pip install pykrx
!pip install conda
!conda install libpython m2w64-toolchain -c msys2
!pip install pystan
!pip install fbprophet

import pyupbit
from pykrx import stock
from fbprophet import Prophet
from fbprophet.plot import add_changepoints_to_plot

#BTC 최근 200시간의 데이터 불러오기
df = pyupbit.get_ohlcv("KRW-BTC", interval="minute60")
print(df)

#시간(ds)와 종가(y)값만 남기기
df = df.reset_index()
df['ds'] = df['index']
df['y'] = df['close']
data = df[['ds', 'y']]

model = Prophet(
    seasonality_mode='multiplicative',
    changepoint_prior_scale=0.5,
    changepoint_range=0.9,
)
model.fit(data)

#24시간예측
future = model.make_future_dataframe(periods=24, freq='H')
forecast = model.predict(future)

#가격 조회
nowValue = pyupbit.get_current_price("KRW-BTC")
closeValue = forecast['yhat'].values[-1]

print("현재가 : " , nowValue)
print("24시간뒤의 가격: ", closeValue)

#그래프 1 
fig1 = model.plot(forecast)
#그래프 2
fig2 = model.plot_components(forecast)